--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: store_auditlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_auditlog (
    id bigint NOT NULL,
    action character varying(100) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    details text NOT NULL,
    cashier_id bigint
);


ALTER TABLE public.store_auditlog OWNER TO postgres;

--
-- Name: store_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.store_category OWNER TO postgres;

--
-- Name: store_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_customer (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    phone character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    loyalty_points integer NOT NULL,
    outstanding_debt numeric(12,2) NOT NULL
);


ALTER TABLE public.store_customer OWNER TO postgres;

--
-- Name: store_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_customerdebtledger; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_customerdebtledger (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    transaction_type character varying(20) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    notes text NOT NULL,
    customer_id bigint NOT NULL,
    sale_id bigint
);


ALTER TABLE public.store_customerdebtledger OWNER TO postgres;

--
-- Name: store_customerdebtledger_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_customerdebtledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_customerdebtledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_product (
    id bigint NOT NULL,
    barcode character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    cost_price numeric(10,2) NOT NULL,
    retail_price numeric(10,2) NOT NULL,
    stock_quantity integer NOT NULL,
    serial_tracked boolean NOT NULL,
    serial_numbers text NOT NULL,
    category_id bigint NOT NULL,
    wholesale_price numeric(10,2) NOT NULL
);


ALTER TABLE public.store_product OWNER TO postgres;

--
-- Name: store_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_purchaseorder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_purchaseorder (
    id bigint NOT NULL,
    date_ordered timestamp with time zone NOT NULL,
    date_received timestamp with time zone,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    supplier_id bigint NOT NULL
);


ALTER TABLE public.store_purchaseorder OWNER TO postgres;

--
-- Name: store_purchaseorder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_purchaseorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_purchaseorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_purchaseorderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_purchaseorderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_cost numeric(10,2) NOT NULL,
    product_id bigint NOT NULL,
    purchase_order_id bigint NOT NULL
);


ALTER TABLE public.store_purchaseorderitem OWNER TO postgres;

--
-- Name: store_purchaseorderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_purchaseorderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_purchaseorderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_returnrefund; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_returnrefund (
    id bigint NOT NULL,
    reason text NOT NULL,
    refund_amount numeric(12,2) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    returned_items text NOT NULL,
    sale_id bigint NOT NULL,
    cashier_id bigint NOT NULL
);


ALTER TABLE public.store_returnrefund OWNER TO postgres;

--
-- Name: store_returnrefund_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_returnrefund ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_returnrefund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_sale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_sale (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    discount numeric(12,2) NOT NULL,
    tax_amount numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    payment_method character varying(50) NOT NULL,
    payment_reference character varying(100) NOT NULL,
    customer_id bigint,
    shift_id bigint NOT NULL,
    cashier_id bigint NOT NULL,
    etims_invoice_number character varying(100) NOT NULL,
    etims_qr_code_data text NOT NULL,
    etims_signature character varying(100) NOT NULL,
    amount_tendered numeric(12,2) NOT NULL,
    change_due numeric(12,2) NOT NULL,
    mixed_cash_amount numeric(12,2) NOT NULL,
    mixed_mpesa_amount numeric(12,2) NOT NULL
);


ALTER TABLE public.store_sale OWNER TO postgres;

--
-- Name: store_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_sale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_saleitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_saleitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    total_price numeric(12,2) NOT NULL,
    serial_numbers text NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL
);


ALTER TABLE public.store_saleitem OWNER TO postgres;

--
-- Name: store_saleitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_saleitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_saleitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_shift; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_shift (
    id bigint NOT NULL,
    open_time timestamp with time zone NOT NULL,
    close_time timestamp with time zone,
    starting_cash numeric(10,2) NOT NULL,
    ending_cash numeric(10,2),
    actual_cash numeric(10,2),
    variance numeric(10,2),
    is_open boolean NOT NULL,
    cashier_id bigint NOT NULL
);


ALTER TABLE public.store_shift OWNER TO postgres;

--
-- Name: store_shift_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_shift ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_shift_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_storeuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_storeuser (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    pin character varying(10) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.store_storeuser OWNER TO postgres;

--
-- Name: store_storeuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_storeuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_storeuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_supplier (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    contact_name character varying(100) NOT NULL,
    phone character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    address text NOT NULL,
    outstanding_balance numeric(12,2) NOT NULL
);


ALTER TABLE public.store_supplier OWNER TO postgres;

--
-- Name: store_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.auth_permission VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission VALUES (5, 'Can add permission', 3, 'add_permission');
INSERT INTO public.auth_permission VALUES (6, 'Can change permission', 3, 'change_permission');
INSERT INTO public.auth_permission VALUES (7, 'Can delete permission', 3, 'delete_permission');
INSERT INTO public.auth_permission VALUES (8, 'Can view permission', 3, 'view_permission');
INSERT INTO public.auth_permission VALUES (9, 'Can add group', 2, 'add_group');
INSERT INTO public.auth_permission VALUES (10, 'Can change group', 2, 'change_group');
INSERT INTO public.auth_permission VALUES (11, 'Can delete group', 2, 'delete_group');
INSERT INTO public.auth_permission VALUES (12, 'Can view group', 2, 'view_group');
INSERT INTO public.auth_permission VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO public.auth_permission VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO public.auth_permission VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO public.auth_permission VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO public.auth_permission VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO public.auth_permission VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO public.auth_permission VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO public.auth_permission VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO public.auth_permission VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO public.auth_permission VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO public.auth_permission VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO public.auth_permission VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO public.auth_permission VALUES (25, 'Can add category', 8, 'add_category');
INSERT INTO public.auth_permission VALUES (26, 'Can change category', 8, 'change_category');
INSERT INTO public.auth_permission VALUES (27, 'Can delete category', 8, 'delete_category');
INSERT INTO public.auth_permission VALUES (28, 'Can view category', 8, 'view_category');
INSERT INTO public.auth_permission VALUES (29, 'Can add customer', 9, 'add_customer');
INSERT INTO public.auth_permission VALUES (30, 'Can change customer', 9, 'change_customer');
INSERT INTO public.auth_permission VALUES (31, 'Can delete customer', 9, 'delete_customer');
INSERT INTO public.auth_permission VALUES (32, 'Can view customer', 9, 'view_customer');
INSERT INTO public.auth_permission VALUES (33, 'Can add purchase order', 12, 'add_purchaseorder');
INSERT INTO public.auth_permission VALUES (34, 'Can change purchase order', 12, 'change_purchaseorder');
INSERT INTO public.auth_permission VALUES (35, 'Can delete purchase order', 12, 'delete_purchaseorder');
INSERT INTO public.auth_permission VALUES (36, 'Can view purchase order', 12, 'view_purchaseorder');
INSERT INTO public.auth_permission VALUES (37, 'Can add shift', 17, 'add_shift');
INSERT INTO public.auth_permission VALUES (38, 'Can change shift', 17, 'change_shift');
INSERT INTO public.auth_permission VALUES (39, 'Can delete shift', 17, 'delete_shift');
INSERT INTO public.auth_permission VALUES (40, 'Can view shift', 17, 'view_shift');
INSERT INTO public.auth_permission VALUES (41, 'Can add store user', 18, 'add_storeuser');
INSERT INTO public.auth_permission VALUES (42, 'Can change store user', 18, 'change_storeuser');
INSERT INTO public.auth_permission VALUES (43, 'Can delete store user', 18, 'delete_storeuser');
INSERT INTO public.auth_permission VALUES (44, 'Can view store user', 18, 'view_storeuser');
INSERT INTO public.auth_permission VALUES (45, 'Can add supplier', 19, 'add_supplier');
INSERT INTO public.auth_permission VALUES (46, 'Can change supplier', 19, 'change_supplier');
INSERT INTO public.auth_permission VALUES (47, 'Can delete supplier', 19, 'delete_supplier');
INSERT INTO public.auth_permission VALUES (48, 'Can view supplier', 19, 'view_supplier');
INSERT INTO public.auth_permission VALUES (49, 'Can add product', 11, 'add_product');
INSERT INTO public.auth_permission VALUES (50, 'Can change product', 11, 'change_product');
INSERT INTO public.auth_permission VALUES (51, 'Can delete product', 11, 'delete_product');
INSERT INTO public.auth_permission VALUES (52, 'Can view product', 11, 'view_product');
INSERT INTO public.auth_permission VALUES (53, 'Can add purchase order item', 13, 'add_purchaseorderitem');
INSERT INTO public.auth_permission VALUES (54, 'Can change purchase order item', 13, 'change_purchaseorderitem');
INSERT INTO public.auth_permission VALUES (55, 'Can delete purchase order item', 13, 'delete_purchaseorderitem');
INSERT INTO public.auth_permission VALUES (56, 'Can view purchase order item', 13, 'view_purchaseorderitem');
INSERT INTO public.auth_permission VALUES (57, 'Can add sale', 15, 'add_sale');
INSERT INTO public.auth_permission VALUES (58, 'Can change sale', 15, 'change_sale');
INSERT INTO public.auth_permission VALUES (59, 'Can delete sale', 15, 'delete_sale');
INSERT INTO public.auth_permission VALUES (60, 'Can view sale', 15, 'view_sale');
INSERT INTO public.auth_permission VALUES (61, 'Can add sale item', 16, 'add_saleitem');
INSERT INTO public.auth_permission VALUES (62, 'Can change sale item', 16, 'change_saleitem');
INSERT INTO public.auth_permission VALUES (63, 'Can delete sale item', 16, 'delete_saleitem');
INSERT INTO public.auth_permission VALUES (64, 'Can view sale item', 16, 'view_saleitem');
INSERT INTO public.auth_permission VALUES (65, 'Can add return refund', 14, 'add_returnrefund');
INSERT INTO public.auth_permission VALUES (66, 'Can change return refund', 14, 'change_returnrefund');
INSERT INTO public.auth_permission VALUES (67, 'Can delete return refund', 14, 'delete_returnrefund');
INSERT INTO public.auth_permission VALUES (68, 'Can view return refund', 14, 'view_returnrefund');
INSERT INTO public.auth_permission VALUES (69, 'Can add audit log', 7, 'add_auditlog');
INSERT INTO public.auth_permission VALUES (70, 'Can change audit log', 7, 'change_auditlog');
INSERT INTO public.auth_permission VALUES (71, 'Can delete audit log', 7, 'delete_auditlog');
INSERT INTO public.auth_permission VALUES (72, 'Can view audit log', 7, 'view_auditlog');
INSERT INTO public.auth_permission VALUES (73, 'Can add customer debt ledger', 10, 'add_customerdebtledger');
INSERT INTO public.auth_permission VALUES (74, 'Can change customer debt ledger', 10, 'change_customerdebtledger');
INSERT INTO public.auth_permission VALUES (75, 'Can delete customer debt ledger', 10, 'delete_customerdebtledger');
INSERT INTO public.auth_permission VALUES (76, 'Can view customer debt ledger', 10, 'view_customerdebtledger');


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.auth_user VALUES (1, 'pbkdf2_sha256$1200000$TFBsI9998iWfqw43DTpx3D$CdicPcQmUPfwFjhVvf4GmBRWHQaio+qITL1tkzN2NV4=', NULL, true, 'admin', '', '', 'admin@example.com', true, true, '2026-08-03 22:52:47.776399+03');


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.django_content_type VALUES (1, 'admin', 'logentry');
INSERT INTO public.django_content_type VALUES (2, 'auth', 'group');
INSERT INTO public.django_content_type VALUES (3, 'auth', 'permission');
INSERT INTO public.django_content_type VALUES (4, 'auth', 'user');
INSERT INTO public.django_content_type VALUES (5, 'contenttypes', 'contenttype');
INSERT INTO public.django_content_type VALUES (6, 'sessions', 'session');
INSERT INTO public.django_content_type VALUES (7, 'store', 'auditlog');
INSERT INTO public.django_content_type VALUES (8, 'store', 'category');
INSERT INTO public.django_content_type VALUES (9, 'store', 'customer');
INSERT INTO public.django_content_type VALUES (10, 'store', 'customerdebtledger');
INSERT INTO public.django_content_type VALUES (11, 'store', 'product');
INSERT INTO public.django_content_type VALUES (12, 'store', 'purchaseorder');
INSERT INTO public.django_content_type VALUES (13, 'store', 'purchaseorderitem');
INSERT INTO public.django_content_type VALUES (14, 'store', 'returnrefund');
INSERT INTO public.django_content_type VALUES (15, 'store', 'sale');
INSERT INTO public.django_content_type VALUES (16, 'store', 'saleitem');
INSERT INTO public.django_content_type VALUES (17, 'store', 'shift');
INSERT INTO public.django_content_type VALUES (18, 'store', 'storeuser');
INSERT INTO public.django_content_type VALUES (19, 'store', 'supplier');


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.django_migrations VALUES (1, 'contenttypes', '0001_initial', '2026-08-03 22:52:31.474441+03');
INSERT INTO public.django_migrations VALUES (2, 'auth', '0001_initial', '2026-08-03 22:52:31.565581+03');
INSERT INTO public.django_migrations VALUES (3, 'admin', '0001_initial', '2026-08-03 22:52:31.600225+03');
INSERT INTO public.django_migrations VALUES (4, 'admin', '0002_logentry_remove_auto_add', '2026-08-03 22:52:31.605463+03');
INSERT INTO public.django_migrations VALUES (5, 'admin', '0003_logentry_add_action_flag_choices', '2026-08-03 22:52:31.611172+03');
INSERT INTO public.django_migrations VALUES (6, 'contenttypes', '0002_remove_content_type_name', '2026-08-03 22:52:31.624866+03');
INSERT INTO public.django_migrations VALUES (7, 'auth', '0002_alter_permission_name_max_length', '2026-08-03 22:52:31.633095+03');
INSERT INTO public.django_migrations VALUES (8, 'auth', '0003_alter_user_email_max_length', '2026-08-03 22:52:31.639683+03');
INSERT INTO public.django_migrations VALUES (9, 'auth', '0004_alter_user_username_opts', '2026-08-03 22:52:31.646311+03');
INSERT INTO public.django_migrations VALUES (10, 'auth', '0005_alter_user_last_login_null', '2026-08-03 22:52:31.65599+03');
INSERT INTO public.django_migrations VALUES (11, 'auth', '0006_require_contenttypes_0002', '2026-08-03 22:52:31.657009+03');
INSERT INTO public.django_migrations VALUES (12, 'auth', '0007_alter_validators_add_error_messages', '2026-08-03 22:52:31.662926+03');
INSERT INTO public.django_migrations VALUES (13, 'auth', '0008_alter_user_username_max_length', '2026-08-03 22:52:31.673157+03');
INSERT INTO public.django_migrations VALUES (14, 'auth', '0009_alter_user_last_name_max_length', '2026-08-03 22:52:31.683745+03');
INSERT INTO public.django_migrations VALUES (15, 'auth', '0010_alter_group_name_max_length', '2026-08-03 22:52:31.691365+03');
INSERT INTO public.django_migrations VALUES (16, 'auth', '0011_update_proxy_permissions', '2026-08-03 22:52:31.697383+03');
INSERT INTO public.django_migrations VALUES (17, 'auth', '0012_alter_user_first_name_max_length', '2026-08-03 22:52:31.703804+03');
INSERT INTO public.django_migrations VALUES (18, 'sessions', '0001_initial', '2026-08-03 22:52:31.714901+03');
INSERT INTO public.django_migrations VALUES (19, 'store', '0001_initial', '2026-08-03 22:52:31.899633+03');
INSERT INTO public.django_migrations VALUES (20, 'store', '0002_remove_customer_joined_date_and_more', '2026-08-03 22:52:31.961207+03');
INSERT INTO public.django_migrations VALUES (21, 'store', '0003_sale_amount_tendered_sale_change_due', '2026-08-03 22:52:31.976031+03');
INSERT INTO public.django_migrations VALUES (22, 'store', '0004_product_wholesale_price_sale_mixed_cash_amount_and_more', '2026-08-03 22:52:31.993839+03');


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_auditlog; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_category; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_customer; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_customerdebtledger; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_product; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_purchaseorder; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_purchaseorderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_returnrefund; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_sale; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_saleitem; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_shift; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_storeuser; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: store_supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: store_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_auditlog_id_seq', 1, false);


--
-- Name: store_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_category_id_seq', 1, false);


--
-- Name: store_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_customer_id_seq', 1, false);


--
-- Name: store_customerdebtledger_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_customerdebtledger_id_seq', 1, false);


--
-- Name: store_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_product_id_seq', 1, false);


--
-- Name: store_purchaseorder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_purchaseorder_id_seq', 1, false);


--
-- Name: store_purchaseorderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_purchaseorderitem_id_seq', 1, false);


--
-- Name: store_returnrefund_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_returnrefund_id_seq', 1, false);


--
-- Name: store_sale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_sale_id_seq', 1, false);


--
-- Name: store_saleitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_saleitem_id_seq', 1, false);


--
-- Name: store_shift_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_shift_id_seq', 1, false);


--
-- Name: store_storeuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_storeuser_id_seq', 1, false);


--
-- Name: store_supplier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.store_supplier_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: store_auditlog store_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_auditlog
    ADD CONSTRAINT store_auditlog_pkey PRIMARY KEY (id);


--
-- Name: store_category store_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_category
    ADD CONSTRAINT store_category_name_key UNIQUE (name);


--
-- Name: store_category store_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_category
    ADD CONSTRAINT store_category_pkey PRIMARY KEY (id);


--
-- Name: store_customer store_customer_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customer
    ADD CONSTRAINT store_customer_phone_key UNIQUE (phone);


--
-- Name: store_customer store_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customer
    ADD CONSTRAINT store_customer_pkey PRIMARY KEY (id);


--
-- Name: store_customerdebtledger store_customerdebtledger_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customerdebtledger
    ADD CONSTRAINT store_customerdebtledger_pkey PRIMARY KEY (id);


--
-- Name: store_product store_product_barcode_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_barcode_key UNIQUE (barcode);


--
-- Name: store_product store_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_pkey PRIMARY KEY (id);


--
-- Name: store_purchaseorder store_purchaseorder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_purchaseorder
    ADD CONSTRAINT store_purchaseorder_pkey PRIMARY KEY (id);


--
-- Name: store_purchaseorderitem store_purchaseorderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_purchaseorderitem
    ADD CONSTRAINT store_purchaseorderitem_pkey PRIMARY KEY (id);


--
-- Name: store_returnrefund store_returnrefund_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_returnrefund
    ADD CONSTRAINT store_returnrefund_pkey PRIMARY KEY (id);


--
-- Name: store_sale store_sale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_sale
    ADD CONSTRAINT store_sale_pkey PRIMARY KEY (id);


--
-- Name: store_saleitem store_saleitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_saleitem
    ADD CONSTRAINT store_saleitem_pkey PRIMARY KEY (id);


--
-- Name: store_shift store_shift_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_shift
    ADD CONSTRAINT store_shift_pkey PRIMARY KEY (id);


--
-- Name: store_storeuser store_storeuser_pin_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_storeuser
    ADD CONSTRAINT store_storeuser_pin_key UNIQUE (pin);


--
-- Name: store_storeuser store_storeuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_storeuser
    ADD CONSTRAINT store_storeuser_pkey PRIMARY KEY (id);


--
-- Name: store_supplier store_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_supplier
    ADD CONSTRAINT store_supplier_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: store_auditlog_cashier_id_6e7d4fba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_auditlog_cashier_id_6e7d4fba ON public.store_auditlog USING btree (cashier_id);


--
-- Name: store_category_name_150032c6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_category_name_150032c6_like ON public.store_category USING btree (name varchar_pattern_ops);


--
-- Name: store_customer_phone_df1c96b8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_customer_phone_df1c96b8_like ON public.store_customer USING btree (phone varchar_pattern_ops);


--
-- Name: store_customerdebtledger_customer_id_cb14ed67; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_customerdebtledger_customer_id_cb14ed67 ON public.store_customerdebtledger USING btree (customer_id);


--
-- Name: store_customerdebtledger_sale_id_d1ef9fd3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_customerdebtledger_sale_id_d1ef9fd3 ON public.store_customerdebtledger USING btree (sale_id);


--
-- Name: store_product_barcode_06b1fff0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_product_barcode_06b1fff0_like ON public.store_product USING btree (barcode varchar_pattern_ops);


--
-- Name: store_product_category_id_574bae65; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_product_category_id_574bae65 ON public.store_product USING btree (category_id);


--
-- Name: store_purchaseorder_supplier_id_fe6c7747; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_purchaseorder_supplier_id_fe6c7747 ON public.store_purchaseorder USING btree (supplier_id);


--
-- Name: store_purchaseorderitem_product_id_b8332699; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_purchaseorderitem_product_id_b8332699 ON public.store_purchaseorderitem USING btree (product_id);


--
-- Name: store_purchaseorderitem_purchase_order_id_0385c6d4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_purchaseorderitem_purchase_order_id_0385c6d4 ON public.store_purchaseorderitem USING btree (purchase_order_id);


--
-- Name: store_returnrefund_cashier_id_a8edd119; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_returnrefund_cashier_id_a8edd119 ON public.store_returnrefund USING btree (cashier_id);


--
-- Name: store_returnrefund_sale_id_9b68fe11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_returnrefund_sale_id_9b68fe11 ON public.store_returnrefund USING btree (sale_id);


--
-- Name: store_sale_cashier_id_1605d5ba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_sale_cashier_id_1605d5ba ON public.store_sale USING btree (cashier_id);


--
-- Name: store_sale_customer_id_9753e13f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_sale_customer_id_9753e13f ON public.store_sale USING btree (customer_id);


--
-- Name: store_sale_shift_id_9af9b237; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_sale_shift_id_9af9b237 ON public.store_sale USING btree (shift_id);


--
-- Name: store_saleitem_product_id_5b1a29d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_saleitem_product_id_5b1a29d7 ON public.store_saleitem USING btree (product_id);


--
-- Name: store_saleitem_sale_id_ce8a288d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_saleitem_sale_id_ce8a288d ON public.store_saleitem USING btree (sale_id);


--
-- Name: store_shift_cashier_id_846c5361; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_shift_cashier_id_846c5361 ON public.store_shift USING btree (cashier_id);


--
-- Name: store_storeuser_pin_4a8f01d8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_storeuser_pin_4a8f01d8_like ON public.store_storeuser USING btree (pin varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_auditlog store_auditlog_cashier_id_6e7d4fba_fk_store_storeuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_auditlog
    ADD CONSTRAINT store_auditlog_cashier_id_6e7d4fba_fk_store_storeuser_id FOREIGN KEY (cashier_id) REFERENCES public.store_storeuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_customerdebtledger store_customerdebtle_customer_id_cb14ed67_fk_store_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customerdebtledger
    ADD CONSTRAINT store_customerdebtle_customer_id_cb14ed67_fk_store_cus FOREIGN KEY (customer_id) REFERENCES public.store_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_customerdebtledger store_customerdebtledger_sale_id_d1ef9fd3_fk_store_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customerdebtledger
    ADD CONSTRAINT store_customerdebtledger_sale_id_d1ef9fd3_fk_store_sale_id FOREIGN KEY (sale_id) REFERENCES public.store_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_product store_product_category_id_574bae65_fk_store_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_category_id_574bae65_fk_store_category_id FOREIGN KEY (category_id) REFERENCES public.store_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_purchaseorder store_purchaseorder_supplier_id_fe6c7747_fk_store_supplier_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_purchaseorder
    ADD CONSTRAINT store_purchaseorder_supplier_id_fe6c7747_fk_store_supplier_id FOREIGN KEY (supplier_id) REFERENCES public.store_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_purchaseorderitem store_purchaseorderi_purchase_order_id_0385c6d4_fk_store_pur; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_purchaseorderitem
    ADD CONSTRAINT store_purchaseorderi_purchase_order_id_0385c6d4_fk_store_pur FOREIGN KEY (purchase_order_id) REFERENCES public.store_purchaseorder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_purchaseorderitem store_purchaseorderitem_product_id_b8332699_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_purchaseorderitem
    ADD CONSTRAINT store_purchaseorderitem_product_id_b8332699_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_returnrefund store_returnrefund_cashier_id_a8edd119_fk_store_storeuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_returnrefund
    ADD CONSTRAINT store_returnrefund_cashier_id_a8edd119_fk_store_storeuser_id FOREIGN KEY (cashier_id) REFERENCES public.store_storeuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_returnrefund store_returnrefund_sale_id_9b68fe11_fk_store_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_returnrefund
    ADD CONSTRAINT store_returnrefund_sale_id_9b68fe11_fk_store_sale_id FOREIGN KEY (sale_id) REFERENCES public.store_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_sale store_sale_cashier_id_1605d5ba_fk_store_storeuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_sale
    ADD CONSTRAINT store_sale_cashier_id_1605d5ba_fk_store_storeuser_id FOREIGN KEY (cashier_id) REFERENCES public.store_storeuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_sale store_sale_customer_id_9753e13f_fk_store_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_sale
    ADD CONSTRAINT store_sale_customer_id_9753e13f_fk_store_customer_id FOREIGN KEY (customer_id) REFERENCES public.store_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_sale store_sale_shift_id_9af9b237_fk_store_shift_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_sale
    ADD CONSTRAINT store_sale_shift_id_9af9b237_fk_store_shift_id FOREIGN KEY (shift_id) REFERENCES public.store_shift(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_saleitem store_saleitem_product_id_5b1a29d7_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_saleitem
    ADD CONSTRAINT store_saleitem_product_id_5b1a29d7_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_saleitem store_saleitem_sale_id_ce8a288d_fk_store_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_saleitem
    ADD CONSTRAINT store_saleitem_sale_id_ce8a288d_fk_store_sale_id FOREIGN KEY (sale_id) REFERENCES public.store_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_shift store_shift_cashier_id_846c5361_fk_store_storeuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_shift
    ADD CONSTRAINT store_shift_cashier_id_846c5361_fk_store_storeuser_id FOREIGN KEY (cashier_id) REFERENCES public.store_storeuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


